apiVersion: apps/v1
kind: Deployment
metadata:
  name: martin-probes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 0134c65e-426b-4ca1-a2a7-190778bdbda9
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 0134c65e-426b-4ca1-a2a7-190778bdbda9
    spec:
      serviceAccountName: martin-probes
      containers:
        - name: main
          image: ghcr.io/martin-deploy-2/probes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 1024Mi
      imagePullSecrets:
        - name: martin-deploy-2-ghcr
